   description: "Daniele Gerosa, mathematician and postdoctoral researcher at Chalmers University of Technology: sampling theory, compressed sensing, signal processing for radar and communications"
   social:
     links:
       - "https://scholar.google.com/citations?user=NWuxsrsAAAAJ"
       - "https://orcid.org/0000-0002-0569-8677"
       - "https://www.linkedin.com/in/daniele-gerosa-941259112/"
       - "https://www.chalmers.se/personer/danieleg/"
